// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/mattjoyce/ductile/internal/scheduler (interfaces: QueueService)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	queue "github.com/mattjoyce/ductile/internal/queue"
)

// MockQueueService is a mock of QueueService interface.
type MockQueueService struct {
	ctrl     *gomock.Controller
	recorder *MockQueueServiceMockRecorder
}

// MockQueueServiceMockRecorder is the mock recorder for MockQueueService.
type MockQueueServiceMockRecorder struct {
	mock *MockQueueService
}

// NewMockQueueService creates a new mock instance.
func NewMockQueueService(ctrl *gomock.Controller) *MockQueueService {
	mock := &MockQueueService{ctrl: ctrl}
	mock.recorder = &MockQueueServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQueueService) EXPECT() *MockQueueServiceMockRecorder {
	return m.recorder
}

// CountOutstandingJobs mocks base method.
func (m *MockQueueService) CountOutstandingJobs(arg0 context.Context, arg1, arg2 string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountOutstandingJobs", arg0, arg1, arg2)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountOutstandingJobs indicates an expected call of CountOutstandingJobs.
func (mr *MockQueueServiceMockRecorder) CountOutstandingJobs(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountOutstandingJobs", reflect.TypeOf((*MockQueueService)(nil).CountOutstandingJobs), arg0, arg1, arg2)
}

// Enqueue mocks base method.
func (m *MockQueueService) Enqueue(arg0 context.Context, arg1 queue.EnqueueRequest) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enqueue", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Enqueue indicates an expected call of Enqueue.
func (mr *MockQueueServiceMockRecorder) Enqueue(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enqueue", reflect.TypeOf((*MockQueueService)(nil).Enqueue), arg0, arg1)
}

// FindJobsByStatus mocks base method.
func (m *MockQueueService) FindJobsByStatus(arg0 context.Context, arg1 queue.Status) ([]*queue.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindJobsByStatus", arg0, arg1)
	ret0, _ := ret[0].([]*queue.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindJobsByStatus indicates an expected call of FindJobsByStatus.
func (mr *MockQueueServiceMockRecorder) FindJobsByStatus(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindJobsByStatus", reflect.TypeOf((*MockQueueService)(nil).FindJobsByStatus), arg0, arg1)
}

// GetCircuitBreaker mocks base method.
func (m *MockQueueService) GetCircuitBreaker(arg0 context.Context, arg1, arg2 string) (*queue.CircuitBreaker, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCircuitBreaker", arg0, arg1, arg2)
	ret0, _ := ret[0].(*queue.CircuitBreaker)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCircuitBreaker indicates an expected call of GetCircuitBreaker.
func (mr *MockQueueServiceMockRecorder) GetCircuitBreaker(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCircuitBreaker", reflect.TypeOf((*MockQueueService)(nil).GetCircuitBreaker), arg0, arg1, arg2)
}

// GetScheduleEntryState mocks base method.
func (m *MockQueueService) GetScheduleEntryState(arg0 context.Context, arg1, arg2 string) (*queue.ScheduleEntryState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetScheduleEntryState", arg0, arg1, arg2)
	ret0, _ := ret[0].(*queue.ScheduleEntryState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetScheduleEntryState indicates an expected call of GetScheduleEntryState.
func (mr *MockQueueServiceMockRecorder) GetScheduleEntryState(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetScheduleEntryState", reflect.TypeOf((*MockQueueService)(nil).GetScheduleEntryState), arg0, arg1, arg2)
}

// LatestCompletedCommandResult mocks base method.
func (m *MockQueueService) LatestCompletedCommandResult(arg0 context.Context, arg1, arg2, arg3 string) (*queue.CommandResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LatestCompletedCommandResult", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*queue.CommandResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LatestCompletedCommandResult indicates an expected call of LatestCompletedCommandResult.
func (mr *MockQueueServiceMockRecorder) LatestCompletedCommandResult(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LatestCompletedCommandResult", reflect.TypeOf((*MockQueueService)(nil).LatestCompletedCommandResult), arg0, arg1, arg2, arg3)
}

// PruneJobLogs mocks base method.
func (m *MockQueueService) PruneJobLogs(arg0 context.Context, arg1 time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PruneJobLogs", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// PruneJobLogs indicates an expected call of PruneJobLogs.
func (mr *MockQueueServiceMockRecorder) PruneJobLogs(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PruneJobLogs", reflect.TypeOf((*MockQueueService)(nil).PruneJobLogs), arg0, arg1)
}

// ResetCircuitBreaker mocks base method.
func (m *MockQueueService) ResetCircuitBreaker(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetCircuitBreaker", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResetCircuitBreaker indicates an expected call of ResetCircuitBreaker.
func (mr *MockQueueServiceMockRecorder) ResetCircuitBreaker(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetCircuitBreaker", reflect.TypeOf((*MockQueueService)(nil).ResetCircuitBreaker), arg0, arg1, arg2)
}

// UpdateJobForRecovery mocks base method.
func (m *MockQueueService) UpdateJobForRecovery(arg0 context.Context, arg1 string, arg2 queue.Status, arg3 int, arg4 *time.Time, arg5 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateJobForRecovery", arg0, arg1, arg2, arg3, arg4, arg5)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateJobForRecovery indicates an expected call of UpdateJobForRecovery.
func (mr *MockQueueServiceMockRecorder) UpdateJobForRecovery(arg0, arg1, arg2, arg3, arg4, arg5 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateJobForRecovery", reflect.TypeOf((*MockQueueService)(nil).UpdateJobForRecovery), arg0, arg1, arg2, arg3, arg4, arg5)
}

// UpsertCircuitBreaker mocks base method.
func (m *MockQueueService) UpsertCircuitBreaker(arg0 context.Context, arg1 queue.CircuitBreaker) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertCircuitBreaker", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertCircuitBreaker indicates an expected call of UpsertCircuitBreaker.
func (mr *MockQueueServiceMockRecorder) UpsertCircuitBreaker(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertCircuitBreaker", reflect.TypeOf((*MockQueueService)(nil).UpsertCircuitBreaker), arg0, arg1)
}

// UpsertScheduleEntryState mocks base method.
func (m *MockQueueService) UpsertScheduleEntryState(arg0 context.Context, arg1 queue.ScheduleEntryState) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertScheduleEntryState", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertScheduleEntryState indicates an expected call of UpsertScheduleEntryState.
func (mr *MockQueueServiceMockRecorder) UpsertScheduleEntryState(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertScheduleEntryState", reflect.TypeOf((*MockQueueService)(nil).UpsertScheduleEntryState), arg0, arg1)
}
