// Code generated by MockGen. DO NOT EDIT.
// Source: internal/scheduler/scheduler.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	queue "github.com/mattjoyce/senechal-gw/internal/queue"
)

// MockQueueService is a mock of QueueService interface.
type MockQueueService struct {
	ctrl     *gomock.Controller
	recorder *MockQueueServiceMockRecorder
}

// MockQueueServiceMockRecorder is the mock recorder for MockQueueService.
type MockQueueServiceMockRecorder struct {
	mock *MockQueueService
}

// NewMockQueueService creates a new mock instance.
func NewMockQueueService(ctrl *gomock.Controller) *MockQueueService {
	mock := &MockQueueService{ctrl: ctrl}
	mock.recorder = &MockQueueServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQueueService) EXPECT() *MockQueueServiceMockRecorder {
	return m.recorder
}

// Enqueue mocks base method.
func (m *MockQueueService) Enqueue(ctx context.Context, req queue.EnqueueRequest) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enqueue", ctx, req)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Enqueue indicates an expected call of Enqueue.
func (mr *MockQueueServiceMockRecorder) Enqueue(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enqueue", reflect.TypeOf((*MockQueueService)(nil).Enqueue), ctx, req)
}

// FindJobsByStatus mocks base method.
func (m *MockQueueService) FindJobsByStatus(ctx context.Context, status queue.Status) ([]*queue.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindJobsByStatus", ctx, status)
	ret0, _ := ret[0].([]*queue.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindJobsByStatus indicates an expected call of FindJobsByStatus.
func (mr *MockQueueServiceMockRecorder) FindJobsByStatus(ctx, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindJobsByStatus", reflect.TypeOf((*MockQueueService)(nil).FindJobsByStatus), ctx, status)
}

// PruneJobLogs mocks base method.
func (m *MockQueueService) PruneJobLogs(ctx context.Context, olderThan time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PruneJobLogs", ctx, olderThan)
	ret0, _ := ret[0].(error)
	return ret0
}

// PruneJobLogs indicates an expected call of PruneJobLogs.
func (mr *MockQueueServiceMockRecorder) PruneJobLogs(ctx, olderThan interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PruneJobLogs", reflect.TypeOf((*MockQueueService)(nil).PruneJobLogs), ctx, olderThan)
}

// UpdateJobForRecovery mocks base method.
func (m *MockQueueService) UpdateJobForRecovery(ctx context.Context, jobID string, status queue.Status, attempt int, nextRetryAt *time.Time, lastError string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateJobForRecovery", ctx, jobID, status, attempt, nextRetryAt, lastError)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateJobForRecovery indicates an expected call of UpdateJobForRecovery.
func (mr *MockQueueServiceMockRecorder) UpdateJobForRecovery(ctx, jobID, status, attempt, nextRetryAt, lastError interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateJobForRecovery", reflect.TypeOf((*MockQueueService)(nil).UpdateJobForRecovery), ctx, jobID, status, attempt, nextRetryAt, lastError)
}
