service:
  name: ductile-docker-if-test
  log_level: debug
  log_format: json
  tick_interval: 1s

state:
  path: ./data/ductile.db

api:
  enabled: true
  listen: "0.0.0.0:8080"
  auth:
    tokens:
      - token: test-admin-token
        scopes: ["*"]

plugin_roots:
  - ./plugins

include:
  - ./plugins.yaml
  - ./pipelines.yaml
